"""Unit tests for rebot_planner.core.ik_core.

Runs on the canonical URDF (KDR-001) with the isaaclab-venv interpreter;
no ROS environment required.
"""

import numpy as np
import pytest

from rebot_planner.core.ik_core import (
    ARM_DOF,
    DEFAULT_TCP_OFFSET_M,
    IK_ERR_ACCEPT,
    KinematicsCore,
    pose_to_transform,
    quat_xyzw_to_rotation,
)

from planner_testlib import make_tcp, rotation_pitch_forward


# ---- model contract ------------------------------------------------------


def test_canonical_velocity_limits(kin):
    """The canonical URDF carries the corrected 5,5,5,3,3,3 rad/s limits."""
    assert np.allclose(kin.velocity_limits, [5.0, 5.0, 5.0, 3.0, 3.0, 3.0])


def test_tcp_offset_is_kdr001(kin):
    T_rel = np.linalg.inv(kin.fk_ee(np.zeros(6))) @ kin.fk_tcp(np.zeros(6))
    assert np.allclose(T_rel[:3, 3], DEFAULT_TCP_OFFSET_M, atol=1e-12)
    assert np.allclose(T_rel[:3, :3], np.eye(3), atol=1e-12)


def test_custom_tcp_transform_wins(urdf_path):
    T_custom = np.eye(4)
    T_custom[:3, 3] = [0.0, 0.0, 0.1]
    k = KinematicsCore(urdf_path, tcp_transform=T_custom)
    T_rel = np.linalg.inv(k.fk_ee(np.zeros(6))) @ k.fk_tcp(np.zeros(6))
    assert np.allclose(T_rel, T_custom, atol=1e-12)


# ---- IK round trip -------------------------------------------------------


def test_ik_round_trip_100_random_reachable_poses(kin):
    """FK(IK(pose)) ~= pose for 100 random reachable targets.

    Targets are generated by FK of random in-limit configurations (0.15 rad
    inside the limits: the projected local solver legitimately stalls when
    the seed-to-target path hugs a joint limit -- that is the guard, not a
    bug); seeds are the target configuration perturbed by up to 0.1 rad per
    joint, the local regime the planner actually uses (waypoint-seeded).
    """
    rng = np.random.default_rng(42)
    lo, hi = kin.lower + 0.15, kin.upper - 0.15
    worst_pos, worst_ang = 0.0, 0.0
    for _ in range(100):
        q_true = rng.uniform(lo, hi)
        T_target = kin.fk_tcp(q_true)
        seed = np.clip(q_true + rng.uniform(-0.1, 0.1, ARM_DOF),
                       kin.lower + 2e-3, kin.upper - 2e-3)
        q_sol, err = kin.solve_tcp(T_target, seed)
        assert err <= IK_ERR_ACCEPT, f"IK residual {err} for q={q_true}"
        assert kin.within_limits(q_sol)
        T_sol = kin.fk_tcp(q_sol)
        dp = float(np.linalg.norm(T_sol[:3, 3] - T_target[:3, 3]))
        R = T_sol[:3, :3].T @ T_target[:3, :3]
        ang = float(np.degrees(
            np.arccos(np.clip((np.trace(R) - 1) / 2, -1.0, 1.0))))
        worst_pos, worst_ang = max(worst_pos, dp), max(worst_ang, ang)
    assert worst_pos < 1.0e-3, f"worst position error {worst_pos * 1e3} mm"
    assert worst_ang < 0.1, f"worst orientation error {worst_ang} deg"


# ---- limit handling ------------------------------------------------------


def test_within_limits_rejects_out_of_range(kin):
    # NOTE: q = 0 is NOT interior -- joint2/joint3 have upper limit 0.0,
    # so the margined check correctly refuses the exact bound.
    assert not kin.within_limits(np.zeros(ARM_DOF))
    q = np.array([0.0, -1.0, -1.0, 0.0, 0.0, 0.0])
    assert kin.within_limits(q)
    q_bad = q.copy()
    q_bad[3] = kin.upper[3] + 0.05
    assert not kin.within_limits(q_bad)
    assert kin.limit_violations(q_bad) == [(4, round(float(q_bad[3]), 3))]
    # exactly on the bound fails the margined check too
    q_edge = q.copy()
    q_edge[5] = kin.upper[5]
    assert not kin.within_limits(q_edge)


def test_solver_never_leaves_the_limits(kin):
    """Projected DLS: every solution is inside the (margined) limits even
    when the target pulls toward a boundary."""
    rng = np.random.default_rng(7)
    for _ in range(20):
        q_true = rng.uniform(kin.lower + 0.05, kin.upper - 0.05)
        T_target = kin.fk_tcp(q_true)
        seed = np.clip(q_true + rng.uniform(-0.3, 0.3, ARM_DOF),
                       kin.lower + 2e-3, kin.upper - 2e-3)
        q_sol, _err = kin.solve_tcp(T_target, seed)
        assert np.all(q_sol >= kin.lower + 1e-3)
        assert np.all(q_sol <= kin.upper - 1e-3)


def test_unreachable_pose_reports_large_residual(kin):
    """A pose far outside the workspace must not be 'accepted'."""
    T = make_tcp(rotation_pitch_forward(0.7), (1.5, 0.0, 0.1))
    _q, err = kin.solve_tcp(T, np.zeros(ARM_DOF))
    assert err > IK_ERR_ACCEPT


# ---- helpers -------------------------------------------------------------


def test_quat_helpers():
    assert np.allclose(quat_xyzw_to_rotation(0, 0, 0, 1), np.eye(3))
    # 90 deg about z
    s = np.sqrt(0.5)
    R = quat_xyzw_to_rotation(0, 0, s, s)
    assert np.allclose(R @ [1, 0, 0], [0, 1, 0], atol=1e-12)
    with pytest.raises(ValueError):
        quat_xyzw_to_rotation(0, 0, 0, 0)
    T = pose_to_transform((1, 2, 3), (0, 0, 0, 1))
    assert np.allclose(T[:3, 3], [1, 2, 3])
